DROP TABLE IF EXISTS USERS CASCADE;
DROP TABLE IF EXISTS BILLINGDETAILS CASCADE;
DROP TABLE IF EXISTS USER_BILLINGDETAILS;

CREATE TABLE USERS(
	ID BIGINT NOT NULL PRIMARY KEY,
	USERNAME VARCHAR(15) NOT NULL UNIQUE,
	ADDRESS_STREET VARCHAR(255) NOT NULL,
	ADDRESS_ZIPCODE VARCHAR(5) NOT NULL,
	ADDRESS_CITY VARCHAR(255) NOT NULL
);

CREATE TABLE BILLINGDETAILS(
	ID BIGINT NOT NULL PRIMARY KEY,
	ACCOUNT VARCHAR(15) NOT NULL,
	BANKNAME VARCHAR(255) NOT NULL,
	USER_ID BIGINT NOT NULL
);

CREATE TABLE USER_BILLINGDETAILS(
	USER_ID BIGINT,
	BILLINGDETAILS_ID BIGINT,
	PRIMARY KEY (USER_ID, BILLINGDETAILS_ID),
	FOREIGN KEY (USER_ID) REFERENCES USERS,
	FOREIGN KEY (BILLINGDETAILS_ID) REFERENCES BILLINGDETAILS
);