services:
  app:
    build: .
    container_name: taco-cloud
    depends_on:
    - mysql
    env_file:
      - ".env"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
    - "8080:8080"
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    ports:
    - ${MYSQL_PORT}:3306
    volumes:
    - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
    