spring:
  application:
    name: license
  doc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui
management:
  endpoints:
    web:
      base-path: /
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: always
  health:
    db:
      enabled: false
    diskspace:
      enabled: true