spring.application.name=taco-cloud
spring.profiles.active=dev

spring.security.oauth2.client.registration.google.client-id=${OAUTH2_GOOGLE_CLIENTID}
spring.security.oauth2.client.registration.google.client-secret=${OAUTH2_GOOGLE_CLIENTSECRET}
spring.security.oauth2.client.registration.google.scope=openid,https://www.googleapis.com/auth/userinfo.email

spring.security.oauth2.client.registration.yandex.client-id=${OAUTH2_YANDEX_CLIENTID}
spring.security.oauth2.client.registration.yandex.client-secret=${OAUTH2_YANDEX_CLIENTSECRET}
spring.security.oauth2.client.registration.yandex.scope=login:email

spring.security.oauth2.client.registration.yandex.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.yandex.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.yandex.client-name=Yandex
spring.security.oauth2.client.registration.yandex.provider=yandex

spring.security.oauth2.client.provider.yandex.authorization-uri=https://oauth.yandex.ru/authorize
spring.security.oauth2.client.provider.yandex.token-uri=https://oauth.yandex.ru/token
spring.security.oauth2.client.provider.yandex.user-info-uri=https://login.yandex.ru/info
spring.security.oauth2.client.provider.yandex.user-name-attribute=id