DROP TABLE IF EXISTS USERS CASCADE;
DROP TABLE IF EXISTS BILLINGDETAILS CASCADE;

CREATE TABLE USERS(
	ID BIGINT NOT NULL PRIMARY KEY,
	USERNAME VARCHAR(15) NOT NULL UNIQUE,
	ADDRESS_STREET VARCHAR(255) NOT NULL,
	ADDRESS_ZIPCODE VARCHAR(5) NOT NULL,
	ADDRESS_CITY VARCHAR(255) NOT NULL
);

CREATE TABLE BILLINGDETAILS(
	ID BIGINT NOT NULL PRIMARY KEY,
	ACCOUNT VARCHAR(15) NOT NULL,
	BANKNAME VARCHAR(255) NOT NULL,
	USER_ID BIGINT NOT NULL,
	FOREIGN KEY (USER_ID) REFERENCES USERS
);