# unique identifier of BTM-server
bitronix.tm.serverId=hibernate-btm

# 2PC logs catalog
bitronix.tm.journal.disk.logPart1Filename=./btm1.tlog
bitronix.tm.journal.disk.logPart2Filename=./btm2.tlog  

# XA DataSource pool configuration
bitronix.tm.resource.ds1.uniqueName=myDS
bitronix.tm.resource.ds1.classname=org.h2.jdbcx.JdbcDataSource
bitronix.tm.resource.ds1.minPoolSize=1
bitronix.tm.resource.ds1.maxPoolSize=5
bitronix.tm.resource.ds1.driverProperties.URL=jdbc:h2:mem:hwdb
bitronix.tm.resource.ds1.driverProperties.user=sa
bitronix.tm.resource.ds1.driverProperties.password=  

# JNDI-factory for BTM
java.naming.factory.initial=bitronix.tm.jndi.BitronixInitialContextFactory